# Generated by Django 4.2.9 on 2025-02-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.productdetail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='products.product'),
        ),
    ]
