# Generated by Django 4.2.9 on 2025-02-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'orders_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': '주문 수령인',
                'verbose_name_plural': '주문 수령인 목록',
                'db_table': 'orders_order_receivers',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productoption')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
                'db_table': 'orders_order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('is_default', models.BooleanField(default=False)),
                ('memo', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 주소',
                'verbose_name_plural': '사용자 주소 목록',
                'db_table': 'orders_order_addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.orderreceiver'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
