# Generated by Django 4.2.9 on 2025-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_first_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
