# Generated by Django 4.2.9 on 2025-02-25 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_is_identified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_identification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '전화번호 신분 증명',
                'verbose_name_plural': '전화번호 신분 증명 목록',
                'db_table': 'accounts_phone_identification',
            },
        ),
        migrations.CreateModel(
            name='EmailIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_identification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이메일 신분 증명',
                'verbose_name_plural': '이메일 신분 증명 목록',
                'db_table': 'accounts_email_identification',
            },
        ),
    ]
